"""
Spreadsheet parser for GiftCardPricingData_2025.xlsx.

Public API:
  parse_workbook(path: Path) -> list[ParsedRow]
  read_global_constants(wb_v) -> GlobalConstants
  slugify(display_name: str) -> str
  classify_row(name_val, b_val, f_val, f_formula) -> str
  extract_formula_refs(formula) -> list[str]
"""

from __future__ import annotations

import re
from collections import Counter
from dataclasses import dataclass
from pathlib import Path
from typing import Literal

from openpyxl import load_workbook

from zeal.models.merchant import MerchantConfig
from zeal.models.pricing import GlobalConstants

PRICING_SHEET = "PricingSheet"
INPUTS_SHEET = "InputsandMargins"

# Column indices in PricingSheet (1-based: A=1 … G=7)
COL_NAME = 1   # A: merchant display name / section label
COL_EBAY = 2   # B: eBay sell-pct input
COL_INMAIL = 3  # C: in_mail_buy output
COL_ELEC = 4   # D: electronic_buy output
COL_INSTORE = 5  # E: in_store_buy output
COL_ONLINE = 6  # F: online_sell output  (mislabeled "Buy" in header)
COL_TIER = 7   # G: tier label

# InputsandMargins row buckets used to classify formula references
_IN_MAIL_MARGIN_ROWS = frozenset({12, 14, 16, 18})
_IN_STORE_MARGIN_ROWS = frozenset({11, 13, 15, 17})
_E_BONUS_ROWS = frozenset({19, 20, 21})
_DIFFERENTIAL_ROWS = frozenset({23, 24})

_MERCH_CREDIT_SUBSTRINGS = frozenset(
    {"merch credit", "merchandise credit", "estore credit", "rebate"}
)

_SECTION_DIVIDER_NAMES = frozenset({"Merchant", "PHYSICAL ONLY", "Bankrupt"})

# Hard-coded slug aliases for known variant rows (recon §7.3).
# All other slugs are generated by the general rule in slugify().
_SLUG_ALIASES: dict[str, str] = {
    "Home Depot Merch Credit (No ID)": "home_depot_merch_credit_no_id",
    "Home Depot Merch Credit (Tied to ID)": "home_depot_merch_credit_with_id",
    "Home Depot eStore Credit": "home_depot_estore_credit",
    "Menards Rebate": "menards_rebate",
    "Lowe's Merch Credit (No ID)": "lowes_merch_credit_no_id",
    "Ikea Merch Credit": "ikea_merch_credit",
    "Target Merch Credit": "target_merch_credit",
    "TJ Maxx / Homegoods / Marshalls Merch Credit": "tjm_homegoods_marshalls_merch_credit",
}

_REF_RE = re.compile(r"InputsandMargins!\$B\$(\d+)")


# ---------------------------------------------------------------------------
# Public data classes
# ---------------------------------------------------------------------------


@dataclass
class SpreadsheetOutputs:
    """Cached values from the four output columns of PricingSheet."""

    online_sell: float | str | None   # str = literal "No"; None = #VALUE!/blank
    in_mail_buy: float | str | None
    in_store_buy: float | str | None
    electronic_buy: float | str | None


@dataclass
class ParsedRow:
    row_number: int
    # "channel_ineligible" is defined in the spec Literal but never emitted —
    # channel eligibility is captured in config flags instead (recon §4.2).
    classification: Literal[
        "normal",
        "no_ebay_data_local",
        "channel_ineligible",
        "bankrupt_broken",
        "section_divider",
        "skip_blank",
    ]
    display_name: str | None
    merchant_id: str | None
    tier: Literal["T24", "C", "Z", "NC"] | None
    ebay_sell_input: float | None
    online_sell_override: float | None
    electronic_buy_override: float | None
    config: MerchantConfig | None
    spreadsheet_outputs: SpreadsheetOutputs | None
    formula_refs: dict[str, list[str]]  # key = channel name, value = ["B23", …]
    notes: list[str]


# ---------------------------------------------------------------------------
# Slug generation  (recon §6, §7.3)
# ---------------------------------------------------------------------------


def slugify(display_name: str) -> str:
    """Return a merchant_id slug for the given display name."""
    if display_name in _SLUG_ALIASES:
        return _SLUG_ALIASES[display_name]
    s = display_name.lower()
    s = re.sub(r"[^a-z0-9]+", "_", s)
    s = re.sub(r"_+", "_", s)
    return s.strip("_")


# ---------------------------------------------------------------------------
# Row classification  (recon §4.6)
# ---------------------------------------------------------------------------


def classify_row(
    name_val: object,
    b_val: object,
    f_val: object,
    f_formula: object,
) -> Literal["normal", "no_ebay_data_local", "bankrupt_broken", "section_divider", "skip_blank"]:
    if not isinstance(name_val, str) or not name_val.strip():
        return "skip_blank"
    if name_val.strip() in _SECTION_DIVIDER_NAMES:
        return "section_divider"
    # F-column is the type signal (decisions_log.md 2026-05-02).
    # Operator-inserted AVERAGE summary rows look numeric in data_only mode but
    # have "=AVERAGE(...)" formulas — detect them before the numeric check.
    if isinstance(f_formula, str) and f_formula.startswith("=AVERAGE("):
        return "section_divider"
    if isinstance(f_formula, str) and f_formula.startswith("="):
        # F is a real formula. It computes correctly for normal rows; it cascades
        # #VALUE! (→ f_val=None) for bankrupt-broken rows where B is text.
        if isinstance(f_val, (int, float)):
            return "normal"
        return "bankrupt_broken"
    # F is a literal number (no formula) — Pattern A merchant with hardcoded online_sell.
    if isinstance(f_formula, (int, float)):
        return "no_ebay_data_local"
    return "bankrupt_broken"


# ---------------------------------------------------------------------------
# Formula reference extraction  (recon §2)
# ---------------------------------------------------------------------------


def extract_formula_refs(formula: object) -> list[str]:
    """Return ['B14', 'B3', …] for every InputsandMargins!$B$n reference."""
    if not isinstance(formula, str):
        return []
    return [f"B{n}" for n in _REF_RE.findall(formula)]


# ---------------------------------------------------------------------------
# InputsandMargins helpers
# ---------------------------------------------------------------------------


def _load_im_values(wb_v: object) -> dict[int, float | None]:
    """Read InputsandMargins column-B values for rows 2–24 (data_only workbook)."""
    ws = wb_v[INPUTS_SHEET]  # type: ignore[index]
    result: dict[int, float | None] = {}
    for row in range(2, 25):
        val = ws.cell(row=row, column=2).value
        result[row] = float(val) if isinstance(val, (int, float)) else None
    return result


def read_global_constants(wb_v: object) -> GlobalConstants:
    """Build GlobalConstants from InputsandMargins cached values (rows 2–10)."""
    im = _load_im_values(wb_v)

    def req(row: int) -> float:
        v = im.get(row)
        if v is None:
            raise ValueError(f"InputsandMargins!B{row} is not numeric")
        return v

    return GlobalConstants(
        ebay_sale_costs=req(2),
        paypal_sell_costs=req(3),
        ebay_postage_costs=req(4),
        online_store_postage_costs=req(5),
        online_sell_bonus_competitive=req(6),
        online_sell_bonus_zen_nocomp=req(7),
        in_store_bad_debt=req(8),
        in_mail_bad_debt=req(9),
        online_bad_debt=req(10),
    )


def _is_merch_credit_variant(display_name: str) -> bool:
    lower = display_name.lower()
    return any(sub in lower for sub in _MERCH_CREDIT_SUBSTRINGS)


def _is_row_empty(ws: object, row: int) -> bool:
    """True when columns A–G are all None for the given row."""
    return all(ws.cell(row=row, column=c).value is None for c in range(1, 8))  # type: ignore[union-attr]


# ---------------------------------------------------------------------------
# Main parser
# ---------------------------------------------------------------------------


def parse_workbook(workbook_path: Path) -> list[ParsedRow]:
    """
    Parse PricingSheet and return one ParsedRow per row starting at row 3.

    Prints a classification summary to stdout after parsing.
    """
    wb_f = load_workbook(workbook_path, data_only=False)  # formula strings
    wb_v = load_workbook(workbook_path, data_only=True)   # cached values

    ws_f = wb_f[PRICING_SHEET]
    ws_v = wb_v[PRICING_SHEET]
    im = _load_im_values(wb_v)

    slug_counts: Counter[str] = Counter()
    rows: list[ParsedRow] = []
    max_row: int = ws_v.max_row or 0

    row = 3  # rows 1–2 are title and headers
    while row <= max_row:
        # Stop when six consecutive rows are completely empty
        if _is_row_empty(ws_v, row) and all(_is_row_empty(ws_v, row + i) for i in range(1, 6)):
            break

        def val(col: int) -> object:
            return ws_v.cell(row=row, column=col).value

        def fml(col: int) -> object:
            return ws_f.cell(row=row, column=col).value

        name_v = val(COL_NAME)
        b_v = val(COL_EBAY)
        f_v = val(COL_ONLINE)
        f_formula_v = fml(COL_ONLINE)

        cls = classify_row(name_v, b_v, f_v, f_formula_v)

        # ---- non-merchant rows -----------------------------------------
        if cls in ("skip_blank", "section_divider"):
            rows.append(
                ParsedRow(
                    row_number=row,
                    classification=cls,
                    display_name=name_v.strip() if isinstance(name_v, str) else None,
                    merchant_id=None,
                    tier=None,
                    ebay_sell_input=None,
                    online_sell_override=None,
                    electronic_buy_override=None,
                    config=None,
                    spreadsheet_outputs=None,
                    formula_refs={},
                    notes=[],
                )
            )
            row += 1
            continue

        # ---- merchant rows ---------------------------------------------
        display_name = name_v.strip() if isinstance(name_v, str) else str(name_v)
        tier_raw = val(COL_TIER)
        tier: Literal["T24", "C", "Z", "NC"] | None = (
            tier_raw if tier_raw in ("T24", "C", "Z", "NC") else None  # type: ignore[assignment]
        )

        base_slug = slugify(display_name)
        slug_counts[base_slug] += 1
        count = slug_counts[base_slug]
        merchant_id = base_slug if count == 1 else f"{base_slug}_{count}"
        notes: list[str] = []
        if count > 1:
            notes.append(f"slug collision: '{base_slug}' used {count} times → '{merchant_id}'")

        # ---- bankrupt-broken ------------------------------------------
        if cls == "bankrupt_broken":
            error_cols = []
            for col_idx, col_label in [
                (COL_ONLINE, "F"),
                (COL_INMAIL, "C"),
                (COL_ELEC, "D"),
                (COL_INSTORE, "E"),
            ]:
                formula = fml(col_idx)
                cached = val(col_idx)
                if isinstance(formula, str) and formula.startswith("=") and cached is None:
                    error_cols.append(col_label)
            error_summary = ",".join(error_cols) if error_cols else "output cells"
            notes.append(f"bankrupt_broken: #VALUE! in {error_summary}")
            rows.append(
                ParsedRow(
                    row_number=row,
                    classification="bankrupt_broken",
                    display_name=display_name,
                    merchant_id=merchant_id,
                    tier=tier,
                    ebay_sell_input=None,
                    online_sell_override=None,
                    electronic_buy_override=None,
                    config=None,
                    spreadsheet_outputs=SpreadsheetOutputs(None, None, None, None),
                    formula_refs={},
                    notes=notes,
                )
            )
            row += 1
            continue

        # ---- normal and no_ebay_data_local ----------------------------
        ebay_sell_input: float | None = float(b_v) if isinstance(b_v, (int, float)) else None

        # Pattern A: F is a hardcoded number (formula-mode shows literal, not "=...")
        # f_formula_v already read before classify_row; reuse it here.
        online_sell_override: float | None = None
        if cls == "no_ebay_data_local":
            if isinstance(f_formula_v, (int, float)):
                online_sell_override = float(f_formula_v)
            elif isinstance(f_v, (int, float)):
                online_sell_override = float(f_v)

        # Formula strings for reference extraction
        c_fml = fml(COL_INMAIL)
        d_fml = fml(COL_ELEC)
        e_fml = fml(COL_INSTORE)

        formula_refs: dict[str, list[str]] = {
            "online_sell": extract_formula_refs(f_formula_v),
            "in_mail_buy": extract_formula_refs(c_fml),
            "in_store_buy": extract_formula_refs(e_fml),
            "electronic_buy": extract_formula_refs(d_fml),
        }

        # Per-channel eligibility: literal "No" in the cell means disabled
        c_v = val(COL_INMAIL)
        d_v = val(COL_ELEC)
        e_v = val(COL_INSTORE)
        in_mail_eligible = not (isinstance(c_v, str) and c_v.strip() == "No")
        electronic_eligible = not (isinstance(d_v, str) and d_v.strip() == "No")
        in_store_eligible = not (isinstance(e_v, str) and e_v.strip() == "No")

        # Derive margin values from formula references + InputsandMargins lookup
        def lookup_im_row(refs: list[str], valid_rows: frozenset[int]) -> float:
            for ref in refs:
                n = int(ref[1:])
                if n in valid_rows:
                    v = im.get(n)
                    if v is not None:
                        return v
            return 0.0

        in_mail_margin = lookup_im_row(formula_refs["in_mail_buy"], _IN_MAIL_MARGIN_ROWS)
        in_store_margin = lookup_im_row(formula_refs["in_store_buy"], _IN_STORE_MARGIN_ROWS)

        e_bonus: float | None = None
        for ref in formula_refs["electronic_buy"]:
            n = int(ref[1:])
            if n in _E_BONUS_ROWS and im.get(n) is not None:
                e_bonus = im[n]
                break

        ebay_differential: float
        diff_refs = formula_refs["online_sell"]
        if diff_refs:
            ebay_differential = lookup_im_row(diff_refs, _DIFFERENTIAL_ROWS)
        else:
            # Pattern A: no formula in F — default to B24 (NC/Zen differential)
            ebay_differential = im.get(24) or 0.025

        # electronic_buy_override: D cell holds a hardcoded number (not a formula, not "No")
        electronic_buy_override: float | None = None
        if isinstance(d_v, (int, float)) and not (isinstance(d_fml, str) and d_fml.startswith("=")):
            electronic_buy_override = float(d_v)
            notes.append(f"electronic_buy_override={electronic_buy_override}")

        if tier is None:
            tier = "NC"
            notes.append("tier missing from column G; defaulted to NC")

        config = MerchantConfig(
            merchant_id=merchant_id,
            display_name=display_name,
            tier=tier,
            in_store_margin=in_store_margin,
            in_mail_margin=in_mail_margin,
            ebay_differential=ebay_differential,
            in_store_eligible=in_store_eligible,
            in_mail_eligible=in_mail_eligible,
            electronic_eligible=electronic_eligible,
            merch_credit_variant=_is_merch_credit_variant(display_name),
            e_bonus=e_bonus,
            online_sell_override=online_sell_override,
            electronic_buy_override=electronic_buy_override,
        )

        def read_output(col: int) -> float | str | None:
            v = ws_v.cell(row=row, column=col).value
            if isinstance(v, (int, float)):
                return float(v)
            if isinstance(v, str):
                return v.strip()
            return None

        spreadsheet_outputs = SpreadsheetOutputs(
            online_sell=read_output(COL_ONLINE),
            in_mail_buy=read_output(COL_INMAIL),
            in_store_buy=read_output(COL_INSTORE),
            electronic_buy=read_output(COL_ELEC),
        )

        rows.append(
            ParsedRow(
                row_number=row,
                classification=cls,
                display_name=display_name,
                merchant_id=merchant_id,
                tier=tier,
                ebay_sell_input=ebay_sell_input,
                online_sell_override=online_sell_override,
                electronic_buy_override=electronic_buy_override,
                config=config,
                spreadsheet_outputs=spreadsheet_outputs,
                formula_refs=formula_refs,
                notes=notes,
            )
        )
        row += 1

    counts = Counter(r.classification for r in rows)
    print("Classification summary:")
    for cls_name in ("normal", "no_ebay_data_local", "bankrupt_broken", "section_divider",
                     "skip_blank"):
        print(f"  {cls_name:<22}: {counts.get(cls_name, 0)}")
    print(f"  {'total':<22}: {len(rows)}")

    return rows
